[239882] Prepare for upgrading Elixir to 1.12
access-company/antikythera pull request #229
Opened 2023-06-07 10:05 UTC by Double-oxygeN

https://acsmine.tok.access-company.com/redmine/issues/239882

2023-06-07 11:12 UTC, aYukiSekiguchi requested changes

2023-06-07 11:38 UTC, aYukiSekiguchi commented on lib/util/crypto.ex
> +    secure_compare_impl(left, right, bxor(bor(acc, x), y))
I found the document
https://hexdocs.pm/elixir/1.11.4/operators.html#operator-precedence-and-associativity

`^^^` have higher precedence than `|||`, so we should call `bxor/2` first then `bor/2`.

2023-06-07 11:55 UTC, aYukiSekiguchi commented on lib/util/crypto.ex
> +    secure_compare_impl(left, right, bxor(bor(acc, x), y))
We should add test cases which use `acc` in https://github.com/access-company/antikythera/blob/master/test/lib/util/crypto_test.exs#L6 like:
```elixi
    assert Crypto.secure_compare("abc", "abc")
    refute Crypto.secure_compare("abc", "aac")
```

Your implementation fails at the second test case.

2023-06-08 01:18 UTC, Double-oxygeN commented on lib/util/crypto.ex
> +    secure_compare_impl(left, right, bxor(bor(acc, x), y))
Sorry, I had a mistake about the operator precedence.
Fixed at aa6ca5b.

2023-06-08 01:19 UTC, Double-oxygeN commented on core/web/template_engine.ex
> +  if Version.match?(System.version(), "~> 1.12") do
Added a comment at 15c565c.

2023-06-08 01:30 UTC, aYukiSekiguchi approved these changes
LGTM

2023-06-08 01:38 UTC, merged