[286905] Migrate from Cacoo diagrams to drawio.png
access-company/antikythera pull request #271
Opened 2024-06-11 01:28 UTC by aDaikiKamata

https://gate.tok.access-company.com/redmine/issues/286905#note-14

2024-06-11 03:29 UTC, Double-oxygeN requested changes

2024-06-11 03:29 UTC, Double-oxygeN commented on doc_src/assets/AntikytheraArchitecture.drawio.png
These symlinks are broken. Please run `mix docs` and check that the images are displayed correctly.

2024-06-17 01:31 UTC, aDaikiKamata commented on doc_src/assets/AntikytheraArchitecture.drawio.png
Sorry, I didn't notice the warnings in the `mix docs`.
Fixed at https://github.com/access-company/antikythera/pull/271/commits/96fd2723800596149a03bb635032cf5dee7ea775 and checked these images display correctly.

I even forgot to delete the `AntikytheraDeploymentFlow.png`.
Fixed at https://github.com/access-company/antikythera/pull/271/commits/e3af5a1e7c118a613e511289170ffd8bc277f7ab.

2024-06-17 01:38 UTC, aDaikiKamata commented
@Double-oxygeN Thank you for your review.
I made some revisions. Would you be able to check them?

2024-06-18 02:51 UTC, Double-oxygeN approved these changes
LGTM

2024-06-20 11:19 UTC, aYukiSekiguchi approved these changes
LGTM

2024-06-20 11:20 UTC, merged